apiVersion: v1
kind: Service
metadata:
  labels:
    run: navab
  name: navab
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31000  
    targetPort: 80
  selector:
    run: navab
  type: NodePort
status:
  loadBalancer: {}
