apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-app
  labels:
    app: stateless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateless
  template:
    metadata:
      labels:
        app: stateless
    spec:
      imagePullSecrets:
      - name: dockerhub-stateless
      containers:
      - name: stateless
        image: navabnaeem/edexa:stateless
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stateless-service
spec:
  selector:
      app: stateless
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJuYXZhYm5hZWVtIiwicGFzc3dvcmQiOiJOYXZhYkAxMDExIiwiYXV0aCI6ImJtRjJZV0p1WVdWbGJUcE9ZWFpoWWtBeE1ERXgifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-stateless
type: kubernetes.io/dockerconfigjson
