apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |

    upstream stateless {
      server stateless-service:80;
    }

    server {

       listen 80;

       server_name stateless.shariff.live;

       location / {
        proxy_pass http://stateless;
       }
    }

    upstream stateful {
      server statefulset-service:80;
    }

    server {

       listen 80;

       server_name stateful.shariff.live;

       location / {
        proxy_pass http://stateful;
       }
    }
